### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by lvagabond** [kawasakizx10rr/HydroController#3]
Hi, your controller is great, but I ran into a few bugs while using it. In the controller log, wrong characters appear or they overlap and another error, when changing the number of dispensers to 4 and then back to 6, it is no longer possible to melt and there is even 16. What is the reason for this? Or is the fault only with my regulator?

![IMG_5793](https://github.com/kawasakizx10rr/HydroController/assets/73300909/3ff9a729-55fd-4cf3-addd-b4695527f1df)
![IMG_5794](https://github.com/kawasakizx10rr/HydroController/assets/73300909/2ed891cd-92b6-4459-bb0d-713ce7f6b871)

**Comment by kawasakizx10rr** [comment]
Oh intresting, it looks as if the char arrays are not being cleared i will fix that today, and the number of dosers looks like the screen clearing for that text is to small, are fix that today too.

**Comment by lvagabond** [comment]
Hi Edwin, I'm glad for your project, it's a wonderful thing. Your last video on YT was a year ago. I thought the project was no longer alive. I tried to contact you by email, but no response. I would be interested in minor software modification and the addition of air heating. I will be happy to support you financially in this project, if it is an acceptable price. Please try to look in the email box and find the sender ***@***.******@***.***
Your work is seriously amazing.
 Thanks again.
Luke

**Comment by kawasakizx10rr** [comment]
4.5.3 is now available, are check my emails tonight to see if i still have it, as im one of those people that wipes my emails every month and i may have not read it, as i have a lot on these day but i am happy to add air heating or whatever, i recently made a AC controller but condensation is a issue if you don't an fresh air intake of at least 10% volume

**Comment by lvagabond** [comment]
Cool job. I'm going to upload it. Thanks a lot

**Comment by kawasakizx10rr** [comment]
I can not find your email so i must have deleted it, can you send it again, and a few minutes after i added my last message i had updated another file which was in debug mode so if you see the sensors are not working, download the code again.

**Comment by lvagabond** [comment]
Good. I'll send the email again in a few minutes, I'll have it in my outbox. Thanks Edwin.

**Comment by lvagabond** [comment]
Try checking Edwin's email.
